name: Docker CI

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: secrets
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run:
          cd container && docker build . --file Dockerfile --tag docker.io/${{ secrets.DOCKERHUB_USERNAME }}/codearkt_http:$(date +%s) --tag docker.io/${{ secrets.DOCKERHUB_USERNAME }}/codearkt_http:latest --push